_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 2
                - 3
                - 12
                - 49
                - 53
            "2":
                - 1
                - 2
                - 3
                - 12
                - 49
                - 53
            "3":
                - 2
                - 14
                - 55
            "4": 3.11.5
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
fc_layer_size:
    value: 32
learning_rate:
    value: 0.002711546963530879
